//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCI_ProcessT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARMAS
    {
        public string cuscod { get; set; }
        public string custyp { get; set; }
        public string prenam { get; set; }
        public string cusnam { get; set; }
        public string addr01 { get; set; }
        public string addr02 { get; set; }
        public string addr03 { get; set; }
        public string zipcod { get; set; }
        public string telnum { get; set; }
        public string contact { get; set; }
        public string cusnam2 { get; set; }
        public string taxid { get; set; }
        public Nullable<double> orgnum { get; set; }
        public string taxtyp { get; set; }
        public Nullable<double> taxrat { get; set; }
        public string taxgrp { get; set; }
        public string taxcond { get; set; }
        public string shipto { get; set; }
        public string slmcod { get; set; }
        public string areacod { get; set; }
        public Nullable<double> paytrm { get; set; }
        public string paycond { get; set; }
        public string payer { get; set; }
        public string tabpr { get; set; }
        public string disc { get; set; }
        public Nullable<double> balance { get; set; }
        public Nullable<double> chqrcv { get; set; }
        public Nullable<double> crline { get; set; }
        public string lasivc { get; set; }
        public string accnum { get; set; }
        public string remark { get; set; }
        public string dlvby { get; set; }
        public string tracksal { get; set; }
        public string creby { get; set; }
        public Nullable<System.DateTime> credat { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> chgdat { get; set; }
        public string status { get; set; }
        public string inactdat { get; set; }
    }
}
