//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCI_ProcessT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OESO> OESO { get; set; }
        public virtual DbSet<OESO_V> OESO_V { get; set; }
        public virtual DbSet<OESOIT> OESOIT { get; set; }
        public virtual DbSet<OESOIT_V> OESOIT_V { get; set; }
        public virtual DbSet<TEST> TEST { get; set; }
        public virtual DbSet<ARMAS> ARMAS { get; set; }
    }
}
