//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCI_ProcessT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OESO_V
    {
        public string SORECTYP { get; set; }
        public string SONUM { get; set; }
        public Nullable<System.DateTime> SODAT { get; set; }
        public string FLGVAT { get; set; }
        public string DEPCOD { get; set; }
        public string SLMCOD { get; set; }
        public string CUSCOD { get; set; }
        public string SHIPTO { get; set; }
        public string YOUREF { get; set; }
        public string RFF { get; set; }
        public string AREACOD { get; set; }
        public Nullable<int> PAYTRM { get; set; }
        public Nullable<System.DateTime> DLVDAT { get; set; }
        public string DLVTIM { get; set; }
        public string DLVDAT_IT { get; set; }
        public string NXTSEQ { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string DISC { get; set; }
        public Nullable<decimal> DISCAMT { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> AMTRAT0 { get; set; }
        public Nullable<decimal> VATRAT { get; set; }
        public Nullable<decimal> VATAMT { get; set; }
        public Nullable<decimal> NETAMT { get; set; }
        public Nullable<decimal> NETVAL { get; set; }
        public Nullable<System.DateTime> CMPLDAT { get; set; }
        public string DOCSTAT { get; set; }
        public string DLVBY { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> CHGDAT { get; set; }
        public string USERPRN { get; set; }
        public Nullable<System.DateTime> PRNDAT { get; set; }
        public Nullable<int> PRNCNT { get; set; }
        public string PRNTIM { get; set; }
        public string AUTHID { get; set; }
        public Nullable<System.DateTime> APPROVE { get; set; }
        public string BILLTO { get; set; }
        public Nullable<int> ORGNUM { get; set; }
    }
}
