//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCI_ProcessT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OESOIT
    {
        public string SORECTYP { get; set; }
        public string SONUM { get; set; }
        public string SEQNUM { get; set; }
        public Nullable<System.DateTime> SODAT { get; set; }
        public Nullable<System.DateTime> DLVDAT { get; set; }
        public string CUSCOD { get; set; }
        public string STKCOD { get; set; }
        public string LOCCOD { get; set; }
        public string STKDES { get; set; }
        public string DEPCOD { get; set; }
        public string VATCOD { get; set; }
        public string FREE { get; set; }
        public Nullable<decimal> ORDQTY { get; set; }
        public Nullable<decimal> CANCELQTY { get; set; }
        public string CANCELTYP { get; set; }
        public Nullable<System.DateTime> CANCELDAT { get; set; }
        public Nullable<decimal> REMQTY { get; set; }
        public Nullable<decimal> TFACTOR { get; set; }
        public Nullable<decimal> UNITPR { get; set; }
        public string TQUCOD { get; set; }
        public string DISC { get; set; }
        public Nullable<decimal> DISCAMT { get; set; }
        public Nullable<decimal> TRNVAL { get; set; }
        public string PACKING { get; set; }
    }
}
